spring:
  application:
    name: tanzu-java-web-app
  datasource:
    url: jdbc:h2:mem:mydb
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  cloud:
    function:
      definition: reservationCreatedReceived;reservationStartedReceived;reservationEndedReceived
    stream:
      default:
        group: fleet
      bindings:
        truck-added:
          destination: truck-added
        truck-inspection-started:
          destination: truck-inspection-started
        truck-inspection-completed:
          destination: truck-inspection-completed
        reservationCreatedReceived-in-0:
          destination: reservation-created
        reservationStartedReceived-in-0:
          destination: reservation-started
        reservationEndedReceived-in-0:
          destination: reservation-ended

management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: always
    