spring:
  application:
    name: tanzu-java-web-app
  datasource:
    url: jdbc:h2:mem:mydb
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  cloud:
    stream:
      bindings:
        truck-added:
          destination: truck-added
        truck-inspection-started:
          destination: truck-inspection-started
        truck-inspection-completed:
          destination: truck-inspection-completed

management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: always
    