apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: lindsey-starter-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: lindsey-starter-web-app
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: 17
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/sample-accelerators/lindsey-starter-web-app
      ref:
        branch: main
  serviceClaims:
  - name: db
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: postgres-2
  - name: rabbitmq
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: rmq-1
