apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: wehaul-fleet
  namespace: wehaul
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: wehaul-fleet
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: 17
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/lmgillaspie/lindsey-starter-web-app
      ref:
        branch: main
  serviceClaims:
  - name: rmq
    ref:
      apiVersion: rabbitmq.com/v1beta1
      kind: RabbitmqCluster
      name: rmq-1